# Generated by Django 3.2.3 on 2021-06-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_auto_20210619_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
